### ISSUE TITLE
Which LiquidCrystal I2C Library is required?

### ISSUE THREAD

**Issue by RolandWijnen** [hms-11/CoopCommand#10]
Hi, 

I've assembled the entire board and I'm now ready to compile the code. Which LiquidCrystal_I2C is required. I've included the one from Frank de Brabander. This gives the compilation error below. Any suggestions? Thanks!

`Arduino: 1.8.12 (Mac OS X), Board: "Arduino Nano, ATmega328P"

Warning: Board breadboard:avr:atmega328bb doesn't define a 'build.board' preference. Auto-set to: AVR_ATMEGA328BB
/Users/roland/Dropbox (Personal)/Smart Living/CoopCommand/CoopCommandWifiRev1/CoopCommandWifiRev1.ino: In function 'void setup()':
CoopCommandWifiRev1:147:13: error: no matching function for call to 'LiquidCrystal_I2C::begin()'
   lcd.begin();
             ^
In file included from /Users/roland/Dropbox (Personal)/Smart Living/CoopCommand/CoopCommandWifiRev1/CoopCommandWifiRev1.ino:22:0:
/Users/roland/Documents/Arduino/libraries/LiquidCrystal_I2C/LiquidCrystal_I2C.h:58:8: note: candidate: void LiquidCrystal_I2C::begin(uint8_t, uint8_t, uint8_t)
   void begin(uint8_t cols, uint8_t rows, uint8_t charsize = LCD_5x8DOTS );

        ^~~~~
/Users/roland/Documents/Arduino/libraries/LiquidCrystal_I2C/LiquidCrystal_I2C.h:58:8: note:   candidate expects 3 arguments, 0 provided
exit status 1
no matching function for call to 'LiquidCrystal_I2C::begin()`

**Comment by hms-11** [comment]
Hello, @RolandWijen
Sorry for the delay in answering, I was away from my computer for the weekend. 
The Library I am using is this one, which seems to be from Fran de Brabander as well so it is likely the same.
https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library

I am working on a windows machine but no idea why that would cause an issue...

Do the example sketches for the library compile without error?

**Comment by RolandWijnen** [comment]
Hi hms-11, 
No worries. Good to know I'm using the correct library. I'll dig into the compile error a little bit deeper. I'll let you know what I find. Thanks for now!

**Comment by RolandWijnen** [comment]
Hi there again, 

I've been working on some other projects in my garden in the meantime. Right now working on CoopCommand again. I was able to compile the code now, also for CoopCam. Both were successfully uploaded to the boards.
